"""Core implementation of env-doctor commands."""

import os
import re
import json
import yaml
import shlex
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import requests

# ---------------------------------------------------------------------------
# Internal utilities
# ---------------------------------------------------------------------------

def _read_env_file(path: str) -> Dict[str, str]:
    """Parse a .env file into a dict. Handles comments, quotes, and multi-line values."""
    result: Dict[str, str] = {}
    path_obj = Path(path)
    if not path_obj.exists():
        raise FileNotFoundError(f"File not found: {path}")
    with open(path_obj, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            # Skip empty lines and comments
            if not line or line.startswith("#"):
                continue
            # Split on first '='
            if "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            # Handle quoted values with shell-like splitting
            if value.startswith('"') and value.endswith('"'):
                try:
                    # Use shlex to handle escapes
                    value = shlex.split(value)[0]
                except (ValueError, IndexError):
                    pass
            result[key] = value
    return result


def _write_env_file(path: str, data: Dict[str, str]) -> None:
    """Write a dict to a .env file."""
    with open(path, "w", encoding="utf-8") as f:
        for key, value in data.items():
            f.write(f"{key}={value}\n")


def _parse_remote_template(content: str) -> Dict[str, str]:
    """Parse remote template content. Supports .env or JSON."""
    content = content.strip()
    if content.startswith("{"):
        try:
            return json.loads(content)
        except json.JSONDecodeError:
            pass
    # Fallback to .env parser
    return _read_env_file_from_text(content)


def _read_env_file_from_text(content: str) -> Dict[str, str]:
    """Parse .env format from a string."""
    result: Dict[str, str] = {}
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        result[key.strip()] = value.strip().strip('"').strip("'")
    return result


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def list_vars(prefix: str = "", sort: bool = False) -> List[Tuple[str, str]]:
    """List environment variables, optionally filtered by prefix."""
    items: List[Tuple[str, str]] = []
    for key, value in os.environ.items():
        if prefix and not key.startswith(prefix):
            continue
        items.append((key, value))
    if sort:
        items.sort(key=lambda x: x[0])
    return items


def check_vars(required: List[str], strict: bool = False) -> Dict[str, bool]:
    """Check that required environment variables exist and are non-empty."""
    results: Dict[str, bool] = {}
    for var in required:
        value = os.environ.get(var, "")
        if strict:
            # In strict mode, require non-empty and no whitespace
            results[var] = bool(value) and not value.isspace()
        else:
            results[var] = bool(value)
    return results


def diff_files(file_a: str, file_b: str) -> List[str]:
    """Compare two config files and return unified diff lines."""
    data_a = _read_env_file(file_a)
    data_b = _read_env_file(file_b)

    diff_lines: List[str] = []
    all_keys = sorted(set(list(data_a.keys()) + list(data_b.keys())))
    for key in all_keys:
        val_a = data_a.get(key, "<missing>")
        val_b = data_b.get(key, "<missing>")
        if val_a != val_b:
            diff_lines.append(f"- {key}={val_a}")
            diff_lines.append(f"+ {key}={val_b}")
    if not diff_lines:
        diff_lines.append("No differences found.")
    return diff_lines


def convert_format(
    input_file: str,
    output_file: str,
    format: str,
    with_comments: bool = False,
) -> None:
    """Convert between .env, JSON, and YAML formats."""
    data = _read_env_file(input_file)

    if format == "json":
        output = json.dumps(data, indent=2, sort_keys=True)
        if with_comments:
            # JSON doesn't support comments, so we prepend a marker line
            output = "// generated by env-doctor\n" + output
    elif format == "yaml":
        output = yaml.dump(data, default_flow_style=False, sort_keys=True)
        if with_comments:
            output = "# generated by env-doctor\n" + output
    elif format == "env":
        lines = []
        for key, value in data.items():
            if with_comments:
                lines.append(f"# {key}")
            lines.append(f"{key}={value}")
        output = "\n".join(lines) + "\n"
    else:
        raise ValueError(f"Unsupported format: {format}")

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(output)


def generate_template(output_file: str, with_comments: bool = False) -> None:
    """Generate a template file from current environment variables."""
    data = list_vars()
    lines = []
    for key, value in data:
        if with_comments:
            lines.append(f"# {key} (example: {value})")
        lines.append(f"{key}=")
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def sync_from_remote(
    remote_url: str,
    apply: bool = False,
    dry_run: bool = False,
    target_file: str = ".env",
) -> Dict[str, Any]:
    """
    Fetch a remote template and optionally apply it to the local .env file.
    Supports both .env and JSON formats from the remote.
    """
    # Fetch remote content
    try:
        response = requests.get(remote_url, timeout=10)
        response.raise_for_status()
        content = response.text
    except requests.RequestException as e:
        raise RuntimeError(f"Failed to fetch remote template: {e}")

    # Parse the template
    template_data = _parse_remote_template(content)

    # Read current .env if it exists
    current_data: Dict[str, str] = {}
    if Path(target_file).exists():
        current_data = _read_env_file(target_file)

    # Compute changes
    added = {k: v for k, v in template_data.items() if k not in current_data}
    removed = {k: v for k, v in current_data.items() if k not in template_data}
    updated = {
        k: v for k, v in template_data.items()
        if k in current_data and current_data[k] != v
    }

    # Apply changes if requested
    if apply and not dry_run:
        merged = dict(current_data)
        merged.update(template_data)  # template overrides
        # Optionally remove keys that are not in template? No, keep existing.
        _write_env_file(target_file, merged)

    # Return summary
    return {
        "added": added,
        "removed": removed,
        "updated": updated,
        "total_template": len(template_data),
        "total_current": len(current_data),
    }


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main(argv: Optional[List[str]] = None) -> int:
    """Command-line interface for env-doctor."""
    import argparse

    parser = argparse.ArgumentParser(description="Environment variable management tool")
    subparsers = parser.add_subparsers(dest="command", required=True)

    # list
    p_list = subparsers.add_parser("list", help="List environment variables")
    p_list.add_argument("--prefix", default="", help="Filter by prefix")
    p_list.add_argument("--sort", action="store_true", help="Sort output")
    p_list.set_defaults(func=list_vars)

    # check
    p_check = subparsers.add_parser("check", help="Check required variables")
    p_check.add_argument("--required", required=True, help="Comma-separated list")
    p_check.add_argument("--strict", action="store_true", help="Strict validation")
    p_check.set_defaults(func=check_vars)

    # diff
    p_diff = subparsers.add_parser("diff", help="Diff two config files")
    p_diff.add_argument("--file-a", required=True, help="First file")
    p_diff.add_argument("--file-b", required=True, help="Second file")
    p_diff.set_defaults(func=diff_files)

    # convert
    p_convert = subparsers.add_parser("convert", help="Convert file format")
    p_convert.add_argument("--input", required=True, help="Input file")
    p_convert.add_argument("--output", required=True, help="Output file")
    p_convert.add_argument("--format", required=True, choices=["json", "yaml", "env"])
    p_convert.add_argument("--with-comments", action="store_true")
    p_convert.set_defaults(func=convert_format)

    # template
    p_template = subparsers.add_parser("template", help="Generate template")
    p_template.add_argument("--output", required=True, help="Output file")
    p_template.add_argument("--with-comments", action="store_true")
    p_template.set_defaults(func=generate_template)

    # sync
    p_sync = subparsers.add_parser("sync", help="Sync from remote template")
    p_sync.add_argument("--remote", required=True, help="Remote template URL")
    p_sync.add_argument("--apply", action="store_true", help="Apply to .env")
    p_sync.add_argument("--dry-run", action="store_true", help="Show changes only")
    p_sync.add_argument("--target-file", default=".env", help="Target file")
    p_sync.set_defaults(func=sync_from_remote)

    args = parser.parse_args(argv)

    # Dispatch
    if args.command == "list":
        items = list_vars(args.prefix, args.sort)
        for k, v in items:
            print(f"{k}={v}")
    elif args.command == "check":
        required = [x.strip() for x in args.required.split(",") if x.strip()]
        results = check_vars(required, args.strict)
        for var, ok in results.items():
            status = "OK" if ok else "MISSING"
            print(f"{var}: {status}")
    elif args.command == "diff":
        lines = diff_files(args.file_a, args.file_b)
        for line in lines:
            print(line)
    elif args.command == "convert":
        convert_format(args.input, args.output, args.format, args.with_comments)
        print(f"Converted {args.input} -> {args.output}")
    elif args.command == "template":
        generate_template(args.output, args.with_comments)
        print(f"Template written to {args.output}")
    elif args.command == "sync":
        result = sync_from_remote(args.remote, args.apply, args.dry_run, args.target_file)
        print(f"Template entries: {result['total_template']}")
        print(f"Current entries: {result['total_current']}")
        print(f"Added: {list(result['added'].keys())}")
        print(f"Removed: {list(result['removed'].keys())}")
        print(f"Updated: {list(result['updated'].keys())}")
        if args.apply and not args.dry_run:
            print(f"Applied to {args.target_file}")
    else:
        parser.print_help()
        return 1
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())