#!/usr/bin/env python3
"""v7.2: LogicReview fixes — HIGH×2, MED×4, LOW×n, attack-point defenses."""
src = open('main.tex').read()

def rep(old, new, count=1):
    global src
    assert src.count(old) == count, f"count={src.count(old)}: {old[:70]!r}"
    src = src.replace(old, new)

# ---- HIGH-1: exactly-one-layer vs L2→L3 ----
rep("Every miss originates in exactly one layer:",
    "Every miss originates in one layer, or in a short chain through adjacent layers:")

# ---- HIGH-2: SS sole-miss 23 -> 17 ----
rep("misses concentrate in reproducible combinations (Caterpillar the sole miss on 118, Cisco 40, SkillSpector 23);",
    "misses concentrate in reproducible combinations---when two scanners agree, the third is the sole miss (Caterpillar 118, Cisco 40, SkillSpector 17), and 39 more skills are flagged by exactly one scanner;")

# ---- MED-3: 79 vs 51 accounting ----
rep("the 79 in Arms 7--13 test the locked hypotheses (three lost their SkillSpector run to scanner-side failures and are excluded from its denominators); Arms 1--6 were exploratory.",
    "the 79 in Arms 7--13 test the locked hypotheses (three lost their SkillSpector run to scanner-side failures and are excluded from its denominators): Table~\\ref{tab:cases} reports the six primary families covering 51 samples, and the remaining 28 (arms 8--10) extend the hidden-file, manifest, and execution-phase families with consistent outcomes. Arms 1--6 were exploratory.")

# ---- MED-4a: census scanner-set overlap ----
rep("\\caption{\\textbf{Disagreement is the norm in the wild.} A market census (project week-0 data, no ground truth; scanner set distinct from \\S\\ref{sec:explain}):",
    "\\caption{\\textbf{Disagreement is the norm in the wild.} A market census (project week-0 data, no ground truth; its six scanners overlap with \\S\\ref{sec:explain}'s three only in SkillSpector):")

# ---- MED-4b: 129 vs 231 disjoint ----
rep("Constructions & 129 (79 conf.) & Prediction validation: Arms 7--13 locked; 1--6 exploratory \\\\",
    "Constructions & 129 (79 conf.) & Prediction validation: Arms 7--13 locked; 1--6 exploratory; disjoint from the corpus above \\\\")

# ---- MED-4c: construction data in observation section -> forward ref ----
rep("Construction results confirm the reading: on the both-declare region, pure-instruction runtime payloads drop Cisco to 22\\% while SkillSpector holds 100\\%; hidden-file payloads drop SkillSpector to 27\\% while remaining visible to YARA-"
    "level rules (a threshold failure, not a gap; \\S\\ref{sec:validate}); removing literal commands blinds the regex engine entirely (0/10) while SkillSpector is unaffected.",
    "The constructions of \\S\\ref{sec:validate} confirm this reading on the both-declare region: each attack form that removes one scanner's surface leaves the others standing (Fig.~\\ref{fig:validation}).")

# ---- MED-5: terminology ----
rep("expression variants evade Cisco on 6/6, and combined strategies evade SkillSpector on 5/5",
    "finding-family variants evade Cisco on 6/6, and combined strategies evade SkillSpector on 5/5")
rep("Malicious corpus & 581 & Observed disagreement: 350 wild + 231 coordinate-generated \\\\",
    "Malicious corpus & 581 & Observed disagreement: 350 wild + 231 generated by occupied coordinate \\\\")
rep("In aggregate the scanners are strong: across 581 malicious skills, SkillSpector flags 92.9\\%, Cisco 86.7\\%, Caterpillar 72.6\\% under a uniform reading of their outputs.",
    "In aggregate the scanners are strong: across 581 malicious skills, SkillSpector flags 92.9\\%, Cisco 86.7\\%, Caterpillar 72.6\\% under a uniform reading of their outputs (any surfaced finding counts; operationalized in Table~\\ref{tab:disagg}).")

# ---- LOW ----
rep("\\emph{For scanner design.} The confirmed blind spots are actionable as engineering fixes, and the decomposition says which kind each is. SkillSpector's dotfile skip is a coverage defect: include hidden files in the build context. Cisco's threshold swallowing is a reporting defect: surface MEDIUM findings instead of discarding them (88 skills in our corpus are \\texttt{is\\_safe} with MEDIUM-or-higher findings).",
    "\\emph{For scanner design.} The confirmed blind spots are actionable as engineering fixes, and the decomposition says which kind each is. SkillSpector's dotfile skip is a coverage defect: include hidden files in the build context. Cisco's threshold swallowing is a reporting defect: surface MEDIUM findings instead of discarding them (88 of the 581 malicious skills are \\texttt{is\\_safe} despite MEDIUM-or-higher findings).")
rep("\\keywords{agent skills, security scanners, taxonomy, blind spots, adversarial construction}",
    "\\keywords{agent skills, security scanners, disagreement analysis, blind spots, adversarial construction}")
rep("(4{,}000 marketplace skills, static runs), Cisco's shipped rule challenges 335 of 3996",
    "(4{,}000 skills; 3{,}996 scanned, 4 rejected as non-UTF-8; static runs), Cisco's shipped rule challenges 335 of 3996")

# ---- attack-point 1: mapping reliability honesty ----
rep("We mapped the documented category systems of six scanners (168 threat categories in total) into the space; the occupied cells consolidate into 43 distinct threat coordinates.",
    "We mapped the documented category systems of six scanners (SkillSpector, Cisco, Snyk, Socket, ATH, AARTS; 168 threat categories in total) into the space; the occupied cells consolidate into 43 distinct threat coordinates. The mapping is single-annotator at this stage; measuring its inter-annotator reliability is part of the extended benchmark this idea paper argues for.")

# ---- attack-point 5: generality preconditions ----
rep("Beyond agent skills, the same loop---observation language, decomposition, locked hypotheses, adversarial validation---applies wherever multiple automated analyses pass judgment on the same artifact and disagree: package registries, dependency scanners, static analyzers, LLM-based security evaluators. Every such setting already produces disagreement; what it lacks is the instrument to read it.",
    "Beyond agent skills, the same loop applies wherever multiple automated analyses judge the same artifact: package registries, dependency scanners, static analyzers, LLM-based security evaluators. Its preconditions are explicit: the threat space must be enumerable into dimensions, and each analysis must expose inspectable outputs (categories, findings, rules) to project---a regex tool with no category system, like our lower-bound reference, cannot be projected at all. Where those hold, the settings already produce disagreement; what they lack is the instrument to read it.")

open('main.tex','w').write(src)
print("v7.2 fixes applied")
